name: Call a other repo

on:
  workflow_dispatch:
    inputs:
      Branch:
        description: 'Enter Sprint branch'
        type: string
        required: true

jobs:
  call-workflow:

    uses: Soorya8docker/ReusableWorkflow/.github/workflows/ReusableWorkflow.yml@main
    with:
      Branch: ${{ inputs.Branch }}
