name: Call a reusable workflow

on:
  workflow_dispatch:
    inputs:
      Branch:
        description: 'Enter Sprint branch'
        type: string
        required: true

jobs:
  call-workflow:
    permissions:
      contents: read
      pull-requests: write
    uses: ./.github/workflows/ReusableWorkflow.yml
    with:
      config-path: .github/labeler.yml
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

    uses: Soorya8docker/ReusableWokflow/.github/workflow/ReusableWorkflow.yml
    with:
      Branch: ${inputs.Branch}
