name: Call a other repo reusable workflow

on:
  workflow_dispatch:
    inputs:
      Branch:
        description: 'Enter Sprint branch'
        type: string
        required: true

jobs:
  call-workflow:
    permissions:
      contents: read
      pull-requests: write
    uses: Soorya8docker/ReusableWorkflow/.github/workflow/ReusableWorkflow.yml
    with:
      Branch: ${{ inputs.Branch }}
